### PR TITLE
SEGA - Stardust Speedway Zone (Past)

### PR DESCRIPTION
**Pull request by LlysiX**
## Chart Verification PR

SEGA - Stardust Speedway Zone (Past)

cover

### Instruments and difficulties charted

| Instrument     | Easy     | Medium    | Hard      | Expert       |
| -------------- | -------- | --------- | --------- | ------------ |
| Drums          | Yes        | Yes        | Yes        | Yes        |
| Bass           | Yes        | Yes        | Yes        | Yes        |
| Lead           | Yes        | Yes        | Yes        | Yes        |
| Vocals         | Yes        | Yes        | Yes        | Yes        |
| Pro Drums      | Yes        | Yes        | Yes        | Yes        |
| Pro Bass       | Yes        | Yes        | Yes        | Yes        |
| Pro Lead       | Yes        | Yes        | Yes        | Yes        |

### Additional details

None

### CODE REVIEW

**Comment by cameron44251** [comment]
image You should definitely make those lift markers match up with the notes below it

**Comment by LlysiX** [comment]
I'm not sure how to feel about this requirement, as this functions normally/as intended in game.

The lifts showing as sustains is a fault of the preview script, and in my opinion should be changed. Markers are not notes, they simply change the function of any/all notes underneath it (e.g. trill/strum lane markers are not a note that can be hit, but change how the notes are hit underneath the marked section).

**Comment by NarrikSynthfox** [comment]
I'd say as long as it functions in game it's fine.

**Comment by 3drosalia** [comment]
I'd still accept it, because the first tick of the lift is all that matters.

**Pull request merged**
